sonar.projectKey=alia-loyzaga_Proyecto_Fitness_Gym
sonar.organization=alia-loyzaga
sonar.token=d46f9d6a84f2cca90966b3c0161b0259064a2d09

sonar.projectName=Proyecto_Fitness_Gym
sonar.projectVersion=1.0

sonar.sources=src
sonar.java.binaries=bin

sonar.sourceEncoding=UTF-8